[env:nrf54l15-halow-dk]
custom_meshtastic_architecture = nrf54l15
custom_meshtastic_hw_model = 255
custom_meshtastic_hw_model_slug = NRF54L15_HALOW_DK
custom_meshtastic_display_name = nRF54L15 HaLow DK
custom_meshtastic_tags = nRF54L15,HaLow,Morse

platform = file:///Users/jasonhao/Documents/GitHub/platform-seeedboards
framework = zephyr
board = nrf54l15dk
upload_protocol = jlink
debug_tool = jlink
monitor_speed = 115200
build_src_filter = -<*>
lib_ignore = MorseWlan

extra_scripts =
  pre:variants/nrf54l15/nrf54l15_halow_dk/pre_build_firmware_nrf54.py

board_build.zephyr.cmake_extra_args =
  -DCONF_FILE=prj.conf;halow.conf
  -DDTC_OVERLAY_FILE=boards/nrf54l15dk_nrf54l15_cpuapp_dk.overlay
  -DKCONFIG_ERROR_ON_WARNINGS=OFF
