[env:nrf54l15-halow-dk]
custom_meshtastic_architecture = nrf54l15
custom_meshtastic_hw_model = 255
custom_meshtastic_hw_model_slug = NRF54L15_HALOW_DK
custom_meshtastic_display_name = nRF54L15 HaLow DK
custom_meshtastic_tags = nRF54L15,HaLow,Morse

platform = file:///Users/jasonhao/Documents/GitHub/platform-seeedboards
framework = zephyr
board = nrf54l15dk
upload_protocol = jlink
debug_tool = jlink
monitor_speed = 115200
build_unflags =
  -std=c++11
  -std=gnu++11
build_flags = ${env.build_flags} -Os
  -std=gnu++17
  -Isrc/platform/nrf54
  -Ivariants/nrf54l15/nrf54l15_halow_dk
  -I.pio/libdeps/nrf54l15-halow-dk/ArduinoThread
  -I.pio/libdeps/nrf54l15-halow-dk/arduino-fsm
  -I.pio/libdeps/nrf54l15-halow-dk/Crypto
  -DARDUINO=100
  -DARCH_NRF54=1
  -DAPP_VERSION=\"nrf54-halow-dev\"
  -DUSERPREFS_TZ_STRING=\"GMT0\"
  -DUSE_HALOW_RADIO=1
  -DUSE_MM_IOT_ZEPHYR=1
  -DHAS_BLUETOOTH=1
  -DMESHTASTIC_EXCLUDE_INPUTBROKER=1
  -DMESHTASTIC_EXCLUDE_GPS=1
  -DMESHTASTIC_EXCLUDE_I2C=1
  -DMESHTASTIC_EXCLUDE_MQTT=1
  -DMESHTASTIC_EXCLUDE_WEBSERVER=1
  -DMESHTASTIC_EXCLUDE_PAXCOUNTER=1
  -DMESHTASTIC_EXCLUDE_ENVIRONMENTAL_SENSOR=1
  -DMESHTASTIC_EXCLUDE_HEALTH_TELEMETRY=1
  -DMESHTASTIC_EXCLUDE_POWERMON=1
  -DMESHTASTIC_EXCLUDE_DROPZONE=1
  -DMESHTASTIC_EXCLUDE_REPLYBOT=1
  -DMESHTASTIC_EXCLUDE_REMOTEHARDWARE=1
  -DMESHTASTIC_EXCLUDE_POWERSTRESS=1
  -DMESHTASTIC_EXCLUDE_GENERIC_THREAD_MODULE=1
build_src_filter =
  -<*>
  +<main.cpp>
  +<platform/nrf54/*.cpp>
lib_ignore = MorseWlan
lib_deps =
  ${env.lib_deps}
  ${radiolib_base.lib_deps}
  rweather/Crypto@0.4.0

extra_scripts =
  pre:variants/nrf54l15/nrf54l15_halow_dk/pre_build_firmware_nrf54.py

board_build.zephyr.cmake_extra_args =
  -DCONF_FILE=prj.conf;halow.conf
  -DDTC_OVERLAY_FILE=boards/nrf54l15dk_nrf54l15_cpuapp_dk.overlay
  -DKCONFIG_ERROR_ON_WARNINGS=OFF
  -DMESHTASTIC_NRF54_FULL_APP=ON
